name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release with current build'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'
        
    - name: Install uv
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://astral.sh/uv/install.ps1 -OutFile install.ps1
        .\install.ps1
        
    - name: Create and activate virtual environment
      shell: pwsh
      run: |
        uv venv zzz-od --python=3.11.9

    - name: Install dependencies
      shell: pwsh
      run: |
        .\zzz-od\Scripts\Activate.ps1
        uv pip install -r requirements-dev.txt
        uv pip install -r requirements-dev-ext.txt
        uv pip compile --annotation-style=line --output-file=requirements-prod.txt requirements-dev.txt
        
    - name: Install PyInstaller
      shell: pwsh
      run: |
        .\zzz-od\Scripts\Activate.ps1
        uv pip install pyinstaller
        
    - name: Download and extract UPX into venv Scripts
      shell: pwsh
      run: |
        $venvScripts = ".\zzz-od\Scripts"
        $upxDir = Join-Path $venvScripts "upx"
        $zipPath = "upx.zip"

        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.3/upx-4.2.3-win64.zip" -OutFile $zipPath
        Expand-Archive -Path $zipPath -DestinationPath $upxDir -Force

    - name: Build executables
      shell: pwsh
      run: |
        .\zzz-od\Scripts\Activate.ps1
        cd deploy
        $upxDir = "..\..\upx\upx-4.2.3-win64"
        pyinstaller --onefile --windowed --uac-admin --icon="../assets/ui/installer_logo.ico" --add-data "../config/project.yml;config" --upx-dir="$upxDir" ../src/zzz_od/gui/zzz_installer.py -n "OneDragon Installer"
        pyinstaller --onefile --uac-admin --icon="../assets/ui/zzz_logo.ico" --upx-dir="$upxDir" ../src/zzz_od/win_exe/full_launcher.py -n "OneDragon Launcher"
        pyinstaller --onefile --uac-admin --icon="../assets/ui/scheduler_logo.ico" --upx-dir="$upxDir" ../src/zzz_od/win_exe/scheduler_launcher.py -n "OneDragon Scheduler"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: |
          deploy/dist/OneDragon Installer.exe
          deploy/dist/OneDragon Launcher.exe
          deploy/dist/OneDragon Scheduler.exe

  release:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.create_release == true || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      shell: pwsh
      run: |
        if ($env:GITHUB_REF -like 'refs/tags/*') {
          $version = $env:GITHUB_REF.Substring(10)
          $tag = $version
        } else {
          $short = $env:GITHUB_SHA.Substring(0,7)
          $date = Get-Date -Format 'yyyyMMdd-HHmmss'
          $tag = "manual-$date-$short"
          $version = $tag
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $tag
          git push origin $tag
        }
        echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "tag=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: executables
        path: deploy/dist

    - name: Prepare release directory and models
      shell: pwsh
      run: |
        function Expand-ZipIntoNamedFolder {
            param (
                [string]$url,
                [string]$downloadPath,
                [string]$destRoot,
                [string]$folderName
            )
            Invoke-WebRequest -Uri $url -OutFile $downloadPath
            $targetPath = Join-Path $destRoot $folderName
            New-Item -ItemType Directory -Path $targetPath -Force
            Expand-Archive -Path $downloadPath -DestinationPath $targetPath -Force
        }

        $distDir = "deploy/dist"
        $rootDir = "$distDir/ZenlessZoneZero-OneDragon"
        New-Item -ItemType Directory -Path $rootDir -Force

        # .env
        $envDir = "$rootDir/.env"
        New-Item -ItemType Directory -Path $envDir -Force
        Invoke-WebRequest -Uri "https://bootstrap.pypa.io/get-pip.py" -OutFile "$envDir/get-pip.py"
        Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.49.0.windows.1/MinGit-2.49.0-busybox-64-bit.zip" -OutFile "$envDir/PortableGit.zip"
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.11.9/python-3.11.9-embed-amd64.zip" -OutFile "$envDir/python-3.11.9-embed-amd64.zip"

        # config
        Copy-Item "config" -Destination $rootDir -Recurse -Force

        # artifact
        Copy-Item "$distDir/OneDragon Installer.exe" -Destination $rootDir -Force
        Copy-Item "$distDir/OneDragon Launcher.exe" -Destination $rootDir -Force
        Copy-Item "$distDir/OneDragon Scheduler.exe" -Destination $rootDir -Force

        # assets
        Copy-Item "assets/ui" -Destination "$rootDir/assets" -Recurse -Force
        Copy-Item "assets/models/onnx_ocr" -Destination "$rootDir/assets/models" -Recurse -Force

        # model route
        $modelBase = "$rootDir/assets/models"
        New-Item -ItemType Directory -Path "$modelBase/flash_classifier" -Force
        New-Item -ItemType Directory -Path "$modelBase/hollow_zero_event" -Force
        New-Item -ItemType Directory -Path "$modelBase/lost_void_det" -Force

        # model name
        $tempDir = "temp_models"
        New-Item -ItemType Directory -Path $tempDir -Force

        Expand-ZipIntoNamedFolder `
          -url "https://github.com/DoctorReid/OneDragon-YOLO/releases/download/zzz_model/yolov8n-640-flash-0127.zip" `
          -downloadPath "$tempDir/flash.zip" `
          -destRoot "$modelBase/flash_classifier" `
          -folderName "yolov8n-640-flash-0127"

        Expand-ZipIntoNamedFolder `
          -url "https://github.com/DoctorReid/OneDragon-YOLO/releases/download/zzz_model/yolov8s-736-hollow-zero-event-0126.zip" `
          -downloadPath "$tempDir/hollow.zip" `
          -destRoot "$modelBase/hollow_zero_event" `
          -folderName "yolov8s-736-hollow-zero-event-0126"

        Expand-ZipIntoNamedFolder `
          -url "https://github.com/DoctorReid/OneDragon-YOLO/releases/download/zzz_model/yolov8n-736-lost-void-det-0125.zip" `
          -downloadPath "$tempDir/lost.zip" `
          -destRoot "$modelBase/lost_void_det" `
          -folderName "yolov8n-736-lost-void-det-0125"

        Remove-Item -Path $tempDir -Recurse -Force

        # tree $rootDir /f > "$distDir/directory-structure.txt"

        # version
        $version = "${{ steps.get_version.outputs.version }}"

        # Pack Full
        Compress-Archive -Path "$rootDir\*" -DestinationPath "$distDir/ZenlessZoneZero-OneDragon-$version-Full.zip" -Force

        # Pack Update
        Compress-Archive -Path @(
          "$rootDir/OneDragon Installer.exe",
          "$rootDir/OneDragon Launcher.exe",
          "$rootDir/OneDragon Scheduler.exe"
        ) -DestinationPath "$distDir/ZenlessZoneZero-OneDragon-$version-Update.zip" -Force

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: "Release ${{ steps.get_version.outputs.version }}"
        files: |
          deploy/dist/ZenlessZoneZero-OneDragon-${{ steps.get_version.outputs.version }}-Full.zip
          deploy/dist/ZenlessZoneZero-OneDragon-${{ steps.get_version.outputs.version }}-Update.zip
          deploy/dist/directory-structure.txt
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
